### ISSUE TITLE
[Keys] move eris-keys names functionality to eris keys (cli level)

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-db#336] opened 2016-10-13 12:58 UTC
**Problem** -- the idea to have human readable names for keys was good. But currently we're managing that within the keys service's data container which we should be treating as more ephemeral. Keys that I actually want to give names to (maybe `caseyPersonal` or `ceoEris` key or whatever) I'll want to be safe on my host rather than in the containers. 

**Solution** -- 
- [ ] remove the eris-keys names functionality from eris-keys completely and move its logic and tests to cli level.
- [ ] add `eris keys names` for working with names. 
- [ ] think about how we can remove friction for users when they need/want specific keys loaded for specific chains or services.

eris-keys side of https://github.com/eris-ltd/eris-cli/issues/795

**Comment by zramsay** [comment] 2017-03-04 04:17
duplicate of https://github.com/eris-ltd/eris/issues/795

**Closed by zramsay** 2017-03-04 04:17 UTC
Labels: area/crypto, triaged, type/technical debt
