### ISSUE TITLE
resolve extra file for arm

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/eris-db#139] opened 2016-06-10 18:18 UTC
see #137 for more info. requires consideration of int/uint

**Comment by benjaminbollen** [comment] 2016-06-10 18:21
also, arm support (above patch on blockchain.go in #137 ) will get lost when we move the re-organised code; so this is a reminder to port it over;

**Comment by zramsay** [comment] 2016-06-10 18:25
hopefully we'll have test for ARM support by then

**Comment by compleatang** [comment] 2016-10-13 18:43
is this (now) a dupe of #251 ?

**Comment by silasdavis** [comment] 2016-11-24 14:46
Yes, closing.

**Closed by silasdavis** 2016-11-24 14:46 UTC
Labels: area/release, triaged
