### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [eris-ltd/eris-db#194] opened 2016-08-06 09:05 UTC
Is it possible to switch Eris product range to a more permissive license like ASL 2.0?

**Comment by zramsay** [comment] 2016-08-06 10:14
duplicate of #148; eris-db will remain GPL3 for the foreseeable future. Please see [this post](https://db.erisindustries.com/products/2015/08/30/on-licensing/) for our rationale.

**Closed by zramsay** 2016-08-06 10:14 UTC

**Comment by zramsay** [comment] 2017-03-04 02:13
@sirinath you'll be glad to hear we've relicensed to Apache 2:
https://github.com/eris-ltd/eris-db/blob/master/license.md
