### ISSUE TITLE
[EVM] Changes to suicide behaviour

### ISSUE THREAD

**Issue by ebuchman** [eris-ltd/eris-db#58] opened 2016-02-29 17:13 UTC
https://github.com/tendermint/tendermint/issues/98

really, sync with eth.

**Comment by compleatang** [comment] 2016-03-20 12:00
@ebuchman can you confirm whether you will be able to close this issue before the end of the month? otherwise we will reassign to Ben or Silas.

**Comment by ebuchman** [comment] 2016-03-20 15:31
happy to stay assigned whether or not I finish by months end. this should be synced with the ethvm work

**Comment by VoR0220** [comment] 2016-03-22 15:23
Keep an eye out, this name has since been changed in solc to selfdestruct...the opcode is on course to change as well IIRC

**Comment by silasdavis** [comment] 2016-10-13 10:48
@ebuchman could you elaborate on what the outcome of this ticket was intended to be?

**Comment by silasdavis** [comment] 2016-11-24 14:21
eris-db contains the changes in vm.go referenced here: https://github.com/tendermint/tendermint/pull/133/files

**Closed by silasdavis** 2016-11-24 14:21 UTC
Labels: area/evm, area/test suite
